server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/tourism_prescription}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tourapi.service-key=${TOUR_API_KEY:e2b5b018b01d88e6d6144f40f7812b1199aea4ac26b6b52c55d56f8af9ba275a}
tourapi.wellness.base-url=http://apis.data.go.kr/B551011/WellnessTursmService
tourapi.wellness.endpoint=/areaBasedList
tourapi.kor.base-url=http://apis.data.go.kr/B551011/KorService2
tourapi.kor.endpoint.area=/areaBasedList2
tourapi.durunubi.base-url=http://apis.data.go.kr/B551011/Durunubi
tourapi.durunubi.endpoint.course=/courseList
tourapi.mobile-os=ETC
tourapi.mobile-app=TourismPrescription
logging.level.com.tour.prescription=DEBUG